### ISSUE TITLE
Update delete_default_argocd_instance function in bootstrap.sh

### ISSUE THREAD

**Issue by hollisc** [cloud-native-toolkit/multi-tenancy-gitops#111]
The current delete_default_argocd_instance function will delete the instance of gitopsservice and argocd CR. This is because the deletion of the gitopsservice instance did not delete the instance of argocd.

delete_default_argocd_instance () {
echo "Delete the default ArgoCD instance"
pushd ${OUTPUT_DIR}
oc delete gitopsservice cluster -n openshift-gitops
oc delete argocd openshift-gitops -n openshift-gitops
popd
}

This has been fixed by the Red Hat team now so the deletion of the gitopsservice will also delete the default instance of ArgoCD. The second delete command can be removed.

**Comment by csantanapr** [comment]
This is fixed now via #112
