### ISSUE TITLE
Add argocd/operators/ibm-automation-foundation-operator.yaml to services in MQ recipe

### ISSUE THREAD

**Issue by stefanvogel65** [cloud-native-toolkit/multi-tenancy-gitops#177]
From my experience trying to run the Quickstart and the MQ Tutorial, I found that I also needed to uncomment the following entry in the `0-bootstrap\single-cluster\2-services\kustomization.yaml`:

``` 
- argocd/operators/ibm-automation-foundation-operator.yaml 
```

You might want to adjust the [MQ recipe](https://github.com/cloud-native-toolkit/multi-tenancy-gitops/blob/master/doc/mq-recipe.md) accordingly.

**Comment by csantanapr** [comment]
Thanks for the feedback @stefanvogel65 , what version of OCP and MQ your trying?

When we did the recipe we didn't this operator, I wonder if anything change maybe with new versions

**Comment by stefanvogel65** [comment]
Hi @csantanapr , I used the one from the MQ Quickstart https://production-gitops.dev/quickstart/quickstart-mq/, i.e. 

* OCP v 4.7.37
* MQ 9.2.3.0-r1

**Comment by hollisc** [comment]
@stefanvogel65, thanks for the feedback.  

@phemankita, I know you recently tested MQ tutorial on OCP 4.8, can you confirm if the install also pulled in `ibm-automation-foundation-operator`?  Like Carlos mentioned, maybe this was changed in the latest version of CP4I.

**Comment by phemankita** [comment]
@hollisc yes we are using that operator as well, `argocd/operators/ibm-automation-foundation-core-operator.yaml` is needed by the MQ tutorial. It was a typo in the guide and this is fixed in this PR https://github.ibm.com/cloudpakbringup/production-deployment-guides/pull/219
