### ISSUE TITLE
Incorrect directory listed in namespace-openshift-storage.yaml

### ISSUE THREAD

**Issue by gormand** [cloud-native-toolkit/multi-tenancy-gitops#26]
When deploying on IBM Cloud I noticed that this dir is not correct https://github.com/cloud-native-toolkit/multi-tenancy-gitops/blob/fe9f718b689bd1b1f7555ffda5a5ba7a1b4c24bb/1-infra/argocd/active/namespace-openshift-storage.yaml#L13

It refers to a directory that doesn't exist, and this shows as errors in ArgoCD.

I'm getting some other errors in ArgoCD which I'm working through.

**Comment by vbudi000** [comment]
Closed by PR #107
